
// Generated by Cadence Genus(TM) Synthesis Solution 17.10-p007_1
// Generated on: May 30 2019 14:29:40 IST (May 30 2019 08:59:40 UTC)

// Verification Directory fv/EC_1 

module EC_1(Input, Clock, Reset, Halt, Output);
  input [7:0] Input;
  input Clock, Reset;
  output Halt;
  output [7:0] Output;
  wire [7:0] Input;
  wire Clock, Reset;
  wire Halt;
  wire [7:0] Output;
  wire [7:0] z2_c2;
  wire [7:0] z2_c1;
  wire [3:0] z2_c3;
  wire [7:5] s3;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, z1_Q0, z1_Q1, z1_Q2, \z2_r_Q[0]_199 , \z2_r_Q[0]_207 ;
  SDFFRHQX1 \z2_a_A_reg[5] (.RN (n_89), .CK (Clock), .D (Output[5]),
       .SI (n_86), .SE (n_88), .Q (Output[5]));
  SDFFRHQX1 \z2_a_A_reg[6] (.RN (n_89), .CK (Clock), .D (Output[6]),
       .SI (n_87), .SE (n_88), .Q (Output[6]));
  SDFFRHQX1 \z2_a_A_reg[1] (.RN (n_89), .CK (Clock), .D (Output[1]),
       .SI (n_84), .SE (n_88), .Q (Output[1]));
  SDFFRHQX1 \z2_a_A_reg[7] (.RN (n_89), .CK (Clock), .D (Output[7]),
       .SI (n_81), .SE (n_88), .Q (Output[7]));
  SDFFRHQX1 \z2_a_A_reg[0] (.RN (n_89), .CK (Clock), .D (Output[0]),
       .SI (n_82), .SE (n_88), .Q (Output[0]));
  SDFFRHQX1 \z2_a_A_reg[4] (.RN (n_89), .CK (Clock), .D (Output[4]),
       .SI (n_79), .SE (n_88), .Q (Output[4]));
  SDFFRHQX1 \z2_a_A_reg[2] (.RN (n_89), .CK (Clock), .D (Output[2]),
       .SI (n_80), .SE (n_88), .Q (Output[2]));
  OAI221X1 g1894__7837(.A0 (Output[6]), .A1 (n_85), .B0 (n_42), .B1
       (n_75), .C0 (n_35), .Y (n_87));
  OAI211X1 g1890__7557(.A0 (n_83), .A1 (n_74), .B0 (n_85), .C0 (n_36),
       .Y (n_86));
  SDFFRHQX1 \z2_a_A_reg[3] (.RN (n_89), .CK (Clock), .D (Output[3]),
       .SI (n_71), .SE (n_88), .Q (Output[3]));
  MX2XL g1895__7654(.A (n_72), .B (Input[1]), .S0 (n_83), .Y (n_84));
  OAI2BB1X1 g1896__8867(.A0N (n_83), .A1N (Input[0]), .B0 (n_77), .Y
       (n_82));
  OAI2BB1X1 g1901__1377(.A0N (n_83), .A1N (Input[7]), .B0 (n_76), .Y
       (n_81));
  OAI2BB1X1 g1900__3717(.A0N (n_83), .A1N (Input[2]), .B0 (n_70), .Y
       (n_80));
  MX2XL g1903__4599(.A (n_68), .B (Input[4]), .S0 (n_83), .Y (n_79));
  SDFFRHQX1 \z2_I_IR_reg[0] (.RN (n_89), .CK (Clock), .D (z2_c2[0]),
       .SI (n_66), .SE (n_78), .Q (z2_c2[0]));
  SDFFRHQX1 \z2_I_IR_reg[1] (.RN (n_89), .CK (Clock), .D (z2_c2[1]),
       .SI (z2_c1[1]), .SE (n_78), .Q (z2_c2[1]));
  SDFFRHQX1 \z2_p_PC_reg[3] (.RN (n_89), .CK (Clock), .D (n_64), .SI
       (z2_c3[3]), .SE (n_73), .Q (z2_c3[3]));
  OAI2BB1X1 g1904__3779(.A0N (n_40), .A1N (n_63), .B0 (n_0), .Y (n_77));
  OAI2BB1X1 g1909__2007(.A0N (n_1), .A1N (n_75), .B0 (n_69), .Y (n_76));
  AOI22X1 g1910__1237(.A0 (Output[6]), .A1 (n_75), .B0 (Output[5]), .B1
       (n_67), .Y (n_74));
  SDFFRHQX1 \z2_p_PC_reg[1] (.RN (n_89), .CK (Clock), .D (n_61), .SI
       (z2_c3[1]), .SE (n_73), .Q (z2_c3[1]));
  OAI2BB1X1 g1907__1297(.A0N (Output[1]), .A1N (Output[0]), .B0 (n_65),
       .Y (n_72));
  OAI21X1 g1908__2006(.A0 (n_83), .A1 (n_58), .B0 (n_37), .Y (n_71));
  AOI32X1 g1911__2833(.A0 (Output[2]), .A1 (n_5), .A2 (n_41), .B0
       (n_20), .B1 (n_62), .Y (n_70));
  NAND2X1 g1920__7547(.A (n_69), .B (n_75), .Y (n_85));
  SDFFRHQX1 \z2_I_IR_reg[6] (.RN (n_89), .CK (Clock), .D (s3[6]), .SI
       (z2_c1[6]), .SE (n_78), .Q (s3[6]));
  SDFFRHQX1 \z2_I_IR_reg[7] (.RN (n_89), .CK (Clock), .D (s3[7]), .SI
       (z2_c1[7]), .SE (n_78), .Q (s3[7]));
  SDFFRHQX1 \z2_p_PC_reg[2] (.RN (n_89), .CK (Clock), .D (n_51), .SI
       (z2_c3[2]), .SE (n_73), .Q (z2_c3[2]));
  OAI22XL g1918__7765(.A0 (n_19), .A1 (n_67), .B0 (n_52), .B1 (n_57),
       .Y (n_68));
  SDFFRHQX1 \z2_I_IR_reg[2] (.RN (n_89), .CK (Clock), .D (z2_c2[2]),
       .SI (z2_c1[2]), .SE (n_78), .Q (z2_c2[2]));
  SDFFRHQX1 \z2_I_IR_reg[5] (.RN (n_89), .CK (Clock), .D (s3[5]), .SI
       (z2_c1[5]), .SE (n_78), .Q (s3[5]));
  SDFFRHQX1 \z2_p_PC_reg[0] (.RN (n_89), .CK (Clock), .D (n_39), .SI
       (z2_c3[0]), .SE (n_73), .Q (z2_c3[0]));
  TBUFXL z2_r_g18__9867(.A (\z2_r_Q[0]_199 ), .OE (n_48), .Y (n_66));
  DFFQXL \z2_r_Q_reg[1] (.CK (Clock), .D (n_49), .Q (z2_c1[1]));
  OAI2BB1X1 g1917__3377(.A0N (n_11), .A1N (n_59), .B0 (n_10), .Y
       (n_65));
  OAI2BB1X1 g1902__9719(.A0N (n_60), .A1N (n_44), .B0 (n_50), .Y
       (n_64));
  INVXL g1921(.A (n_62), .Y (n_63));
  DFFRHQX1 z1_f3_q_reg(.RN (n_89), .CK (Clock), .D (n_55), .Q (z1_Q0));
  NOR2X1 g1925__1591(.A (Output[5]), .B (n_67), .Y (n_75));
  MX2XL g1932__6789(.A (z2_c2[1]), .B (n_38), .S0 (n_60), .Y (n_61));
  NOR2X1 g1924__5927(.A (n_83), .B (n_59), .Y (n_62));
  AOI22X1 g1930__2001(.A0 (n_45), .A1 (n_57), .B0 (Output[3]), .B1
       (n_27), .Y (n_58));
  OAI221X1 g1931__1122(.A0 (n_2), .A1 (n_46), .B0 (n_9), .B1 (n_53),
       .C0 (n_29), .Y (n_56));
  DFFRHQX1 z1_f2_q_reg(.RN (n_89), .CK (Clock), .D (n_47), .Q (z1_Q2));
  DFFQXL \z2_r_Q_reg[6] (.CK (Clock), .D (n_30), .Q (z2_c1[6]));
  NAND3BXL g1938__2005(.AN (Halt), .B (n_22), .C (n_53), .Y (n_55));
  NAND2X1 g1935__9771(.A (n_52), .B (n_57), .Y (n_67));
  DFFQXL \z2_r_Q_reg[7] (.CK (Clock), .D (n_31), .Q (z2_c1[7]));
  OAI2BB1X1 g1916__3457(.A0N (n_60), .A1N (n_23), .B0 (n_50), .Y
       (n_51));
  DFFQXL \z2_r_Q_reg[0] (.CK (Clock), .D (n_34), .Q (\z2_r_Q[0]_199 ));
  OAI21XL g1928__1279(.A0 (n_25), .A1 (n_43), .B0 (n_32), .Y (n_49));
  INVX1 g1942(.A (\z2_r_Q[0]_207 ), .Y (n_48));
  NAND2BXL g1949__6179(.AN (Halt), .B (n_46), .Y (n_47));
  DFFQXL \z2_r_Q_reg[5] (.CK (Clock), .D (n_18), .Q (z2_c1[5]));
  NOR2X1 g1939__7837(.A (Output[3]), .B (n_45), .Y (n_59));
  AOI21X1 g1940__7557(.A0 (Output[0]), .A1 (n_28), .B0 (n_78), .Y
       (n_73));
  OAI21XL g1919__7654(.A0 (n_33), .A1 (n_43), .B0 (n_16), .Y (n_44));
  NAND2XL g1955__8867(.A (Output[6]), .B (n_41), .Y (n_42));
  OAI21X1 g1958__1377(.A0 (Output[1]), .A1 (Output[2]), .B0 (n_41), .Y
       (n_40));
  DFFQXL \z2_r_Q_reg[2] (.CK (Clock), .D (n_21), .Q (z2_c1[2]));
  OAI21X1 g1961__3717(.A0 (z1_Q1), .A1 (n_8), .B0 (n_41), .Y (n_88));
  MX2XL g1937__4599(.A (z2_c2[0]), .B (n_3), .S0 (n_60), .Y (n_39));
  INVX1 g1941(.A (n_26), .Y (n_38));
  NAND2X1 g1946__3779(.A (n_83), .B (Input[3]), .Y (n_37));
  DFFQXL \z2_r_Q_reg[0]19 (.CK (Clock), .D (n_13), .Q (\z2_r_Q[0]_207
       ));
  NAND2X1 g1948__2007(.A (n_83), .B (Input[5]), .Y (n_36));
  NAND2X1 g1950__1237(.A (n_83), .B (Input[6]), .Y (n_35));
  OAI31X1 g1927__1297(.A0 (z2_c3[3]), .A1 (z2_c3[2]), .A2 (n_33), .B0
       (n_32), .Y (n_34));
  OAI21XL g1957__2006(.A0 (z2_c3[3]), .A1 (n_12), .B0 (n_32), .Y
       (n_31));
  OAI21XL g1954__2833(.A0 (n_24), .A1 (n_43), .B0 (n_17), .Y (n_30));
  NOR2XL g1956__7547(.A (Halt), .B (n_78), .Y (n_29));
  NAND2X1 g1960__7765(.A (z2_c2[2]), .B (n_28), .Y (n_50));
  NOR2BX1 g1951__9867(.AN (Output[7]), .B (n_83), .Y (n_69));
  NOR2X1 g1952__3377(.A (Output[3]), .B (n_27), .Y (n_57));
  ADDHX1 g1943__9719(.A (z2_c3[0]), .B (n_24), .CO (n_25), .S (n_26));
  MXI2XL g1953__1591(.A (z2_c3[2]), .B (n_15), .S0 (n_33), .Y (n_23));
  OAI2BB1X1 g1944__6789(.A0N (z1_Q1), .A1N (n_4), .B0 (n_14), .Y
       (n_22));
  INVXL g1933(.A (n_32), .Y (n_21));
  INVX1 g1962(.A (n_27), .Y (n_20));
  NAND2X1 g1959__5927(.A (n_52), .B (n_19), .Y (n_45));
  OAI21XL g1970__2001(.A0 (z2_c3[1]), .A1 (z2_c3[3]), .B0 (n_17), .Y
       (n_18));
  OAI21X1 g1929__1122(.A0 (n_15), .A1 (n_33), .B0 (z2_c3[3]), .Y
       (n_16));
  NAND3X1 g1971__2005(.A (s3[7]), .B (z1_Q1), .C (n_14), .Y (n_46));
  NAND3X1 g1973__9771(.A (s3[6]), .B (s3[5]), .C (n_14), .Y (n_53));
  INVX1 g1963(.A (n_83), .Y (n_41));
  NOR2XL g1964__3457(.A (n_6), .B (n_12), .Y (n_13));
  NAND2X1 g1965__1279(.A (n_11), .B (n_10), .Y (n_27));
  NAND2X1 g1966__6179(.A (z2_c3[3]), .B (n_12), .Y (n_32));
  INVX1 g1969(.A (n_60), .Y (n_28));
  NOR2X1 g1967__7837(.A (n_9), .B (n_8), .Y (Halt));
  NOR2X1 g1975__7557(.A (z1_Q1), .B (n_7), .Y (n_78));
  NOR2X1 g1968__7654(.A (n_9), .B (n_7), .Y (n_83));
  NAND2X1 g1984__8867(.A (z2_c3[2]), .B (n_6), .Y (n_43));
  NAND3BX1 g1974__1377(.AN (z1_Q0), .B (z1_Q2), .C (z1_Q1), .Y (n_60));
  INVX1 g1976(.A (n_10), .Y (n_5));
  NOR3X1 g1972__3717(.A (Output[5]), .B (Output[7]), .C (Output[6]), .Y
       (n_19));
  INVX1 g1981(.A (n_12), .Y (n_17));
  NAND2XL g1977__4599(.A (s3[7]), .B (s3[5]), .Y (n_4));
  NOR2X1 g1983__3779(.A (z1_Q0), .B (z1_Q2), .Y (n_14));
  NOR2X1 g1979__2007(.A (Output[1]), .B (Output[0]), .Y (n_10));
  NAND2BX1 g1982__1237(.AN (z1_Q2), .B (z1_Q0), .Y (n_7));
  NAND2X1 g1978__1297(.A (z1_Q0), .B (z1_Q2), .Y (n_8));
  NOR2X1 g1985__2006(.A (z2_c3[1]), .B (z2_c3[2]), .Y (n_12));
  NAND2X1 g1980__2833(.A (z2_c3[1]), .B (z2_c3[0]), .Y (n_33));
  INVXL g1987(.A (z2_c3[0]), .Y (n_3));
  INVX1 g1992(.A (s3[6]), .Y (n_2));
  INVX1 g1988(.A (Output[2]), .Y (n_11));
  INVX1 g1994(.A (z2_c3[2]), .Y (n_15));
  INVXL g1996(.A (Reset), .Y (n_89));
  INVXL g1990(.A (Output[6]), .Y (n_1));
  INVX1 g1993(.A (Output[0]), .Y (n_0));
  INVX1 g1989(.A (z2_c3[1]), .Y (n_24));
  INVX1 g1991(.A (z2_c3[3]), .Y (n_6));
  INVX1 g1986(.A (Output[4]), .Y (n_52));
  DFFRX1 z1_f1_q_reg(.RN (n_89), .CK (Clock), .D (n_56), .Q (z1_Q1),
       .QN (n_9));
endmodule

